{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "19e5b09e-c305-499c-8826-d401357b20d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import io\n",
    "import time\n",
    "import jwt\n",
    "import requests\n",
    "import pandas as pd\n",
    "import psycopg2\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "# =====================================================\n",
    "# CONFIG\n",
    "# =====================================================\n",
    "\n",
    "API_KEY = os.getenv(\"API_KEY\")\n",
    "SECRET_KEY = os.getenv(\"SECRET_KEY\")\n",
    "\n",
    "DB_HOST = os.getenv(\"DB_HOST\")\n",
    "DB_NAME = os.getenv(\"DB_NAME\")\n",
    "DB_USER = os.getenv(\"DB_USER\")\n",
    "DB_PASSWORD = os.getenv(\"DB_PASSWORD\")\n",
    "DB_PORT = os.getenv(\"DB_PORT\", 5432)\n",
    "\n",
    "TABLE_NAME = \"sales\"   # change if needed\n",
    "\n",
    "# yesterday business load by default\n",
    "LOAD_DATE = (datetime.today() - timedelta(days=1)).strftime(\"%Y-%m-%d\")\n",
    "\n",
    "# =====================================================\n",
    "# AUTH TOKEN\n",
    "# =====================================================\n",
    "\n",
    "def get_token():\n",
    "    payload = {\n",
    "        \"iss\": API_KEY,\n",
    "        \"iat\": int(time.time())\n",
    "    }\n",
    "    return jwt.encode(payload, SECRET_KEY, algorithm=\"HS256\")\n",
    "\n",
    "\n",
    "def headers():\n",
    "    return {\n",
    "        \"x-api-key\": API_KEY,\n",
    "        \"x-api-token\": get_token(),\n",
    "        \"content-type\": \"application/json\"\n",
    "    }\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# API FETCH\n",
    "# =====================================================\n",
    "\n",
    "def get_branches():\n",
    "    print(\"Fetching branch list...\")\n",
    "\n",
    "    url = \"https://api.ristaapps.com/v1/branch/list\"\n",
    "\n",
    "    response = requests.get(\n",
    "        url,\n",
    "        headers=headers(),\n",
    "        timeout=60\n",
    "    )\n",
    "\n",
    "    response.raise_for_status()\n",
    "\n",
    "    branches = [\n",
    "        b[\"branchCode\"]\n",
    "        for b in response.json()\n",
    "        if \"branchCode\" in b\n",
    "    ]\n",
    "\n",
    "    print(f\"Total branches found: {len(branches)}\")\n",
    "\n",
    "    return branches\n",
    "\n",
    "\n",
    "def fetch_sales_summary(branch, day):\n",
    "    url = \"https://api.ristaapps.com/v1/sales/summary\"\n",
    "\n",
    "    params = {\n",
    "        \"branch\": branch,\n",
    "        \"day\": day\n",
    "    }\n",
    "\n",
    "    all_data = []\n",
    "\n",
    "    while True:\n",
    "        response = requests.get(\n",
    "            url,\n",
    "            headers=headers(),\n",
    "            params=params,\n",
    "            timeout=120\n",
    "        )\n",
    "\n",
    "        response.raise_for_status()\n",
    "\n",
    "        js = response.json()\n",
    "\n",
    "        all_data.extend(js.get(\"data\", []))\n",
    "\n",
    "        if not js.get(\"lastKey\"):\n",
    "            break\n",
    "\n",
    "        params[\"lastKey\"] = js[\"lastKey\"]\n",
    "\n",
    "    return all_data\n",
    "\n",
    "\n",
    "def get_all_sales(day):\n",
    "    all_sales = []\n",
    "    branches = get_branches()\n",
    "\n",
    "    for branch in branches:\n",
    "        try:\n",
    "            print(f\"Fetching sales for: {branch}\")\n",
    "\n",
    "            branch_data = fetch_sales_summary(branch, day)\n",
    "            all_sales.extend(branch_data)\n",
    "\n",
    "            print(f\"Rows fetched: {len(branch_data)}\")\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"Failed branch {branch}: {str(e)}\")\n",
    "\n",
    "    df = pd.DataFrame(all_sales)\n",
    "\n",
    "    print(f\"Total rows fetched: {len(df)}\")\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# DATA CLEANING\n",
    "# =====================================================\n",
    "\n",
    "def process_data(df):\n",
    "    print(\"Processing data...\")\n",
    "\n",
    "    if df.empty:\n",
    "        raise Exception(\"No data fetched from API\")\n",
    "\n",
    "    # remove unwanted columns if exists\n",
    "    drop_cols = [\"saleBy\", \"label\", \"tipAmount\"]\n",
    "    existing_drop_cols = [c for c in drop_cols if c in df.columns]\n",
    "    df = df.drop(columns=existing_drop_cols)\n",
    "\n",
    "    # datetime handling\n",
    "    df[\"invoiceDate\"] = pd.to_datetime(\n",
    "        df[\"invoiceDate\"],\n",
    "        errors=\"coerce\"\n",
    "    )\n",
    "\n",
    "    df[\"Hour\"] = df[\"invoiceDate\"].dt.hour.astype(\"Int64\")\n",
    "\n",
    "    # business date logic (till 6AM previous day)\n",
    "    df[\"BusinessDate\"] = (\n",
    "        df[\"invoiceDate\"] - pd.Timedelta(hours=6)\n",
    "    ).dt.date\n",
    "\n",
    "    df[\"date\"] = df[\"invoiceDate\"].dt.date\n",
    "\n",
    "    # lowercase channel safely\n",
    "    cl = df[\"channel\"].fillna(\"\").astype(str).str.lower()\n",
    "\n",
    "    df[\"BusinessBrand\"] = cl.apply(\n",
    "        lambda x:\n",
    "            \"Frozen Bottle\" if \"frozen bottle\" in x else\n",
    "            \"Madno\" if \"madno\" in x else\n",
    "            \"Lubov\" if \"lubov\" in x else\n",
    "            \"Boba Bar\" if \"boba bar\" in x else\n",
    "            \"Unknown\"\n",
    "    )\n",
    "\n",
    "    df[\"Source\"] = cl.apply(\n",
    "        lambda x:\n",
    "            \"In-Store\" if \"store\" in x else\n",
    "            \"Swiggy\" if \"swiggy\" in x else\n",
    "            \"Zomato\" if \"zomato\" in x else\n",
    "            \"Ownly\" if \"ownly\" in x else\n",
    "            \"Other\"\n",
    "    )\n",
    "\n",
    "    df[\"Channel_Category\"] = cl.apply(\n",
    "        lambda x:\n",
    "            \"Offline\" if \"store\" in x else\n",
    "            \"Online\"\n",
    "    )\n",
    "\n",
    "    correct_cols = [\n",
    "        \"branchName\",\n",
    "        \"branchCode\",\n",
    "        \"invoiceNumber\",\n",
    "        \"invoiceDate\",\n",
    "        \"invoiceType\",\n",
    "        \"directChargeAmount\",\n",
    "        \"chargeAmount\",\n",
    "        \"grossAmount\",\n",
    "        \"discountAmount\",\n",
    "        \"taxAmount\",\n",
    "        \"netAmount\",\n",
    "        \"roundOffAmount\",\n",
    "        \"totalAmount\",\n",
    "        \"channel\",\n",
    "        \"status\",\n",
    "        \"sessionLabel\",\n",
    "        \"customerId\",\n",
    "        \"customerName\",\n",
    "        \"Hour\",\n",
    "        \"BusinessDate\",\n",
    "        \"date\",\n",
    "        \"BusinessBrand\",\n",
    "        \"Source\",\n",
    "        \"Channel_Category\"\n",
    "    ]\n",
    "\n",
    "    df = df.reindex(columns=correct_cols)\n",
    "\n",
    "    df = df.replace(\"\", None)\n",
    "\n",
    "    print(\"Data processing completed.\")\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# DB LOAD\n",
    "# =====================================================\n",
    "\n",
    "def get_connection():\n",
    "    print(\"Connecting to Neon DB...\")\n",
    "\n",
    "    conn = psycopg2.connect(\n",
    "        host=DB_HOST,\n",
    "        database=DB_NAME,\n",
    "        user=DB_USER,\n",
    "        password=DB_PASSWORD,\n",
    "        port=DB_PORT,\n",
    "        sslmode=\"require\"\n",
    "    )\n",
    "\n",
    "    print(\"Database connected successfully.\")\n",
    "\n",
    "    return conn\n",
    "\n",
    "\n",
    "def load_to_postgres(df):\n",
    "    conn = None\n",
    "    cursor = None\n",
    "\n",
    "    try:\n",
    "        conn = get_connection()\n",
    "        cursor = conn.cursor()\n",
    "\n",
    "        load_date = df[\"BusinessDate\"].iloc[0]\n",
    "\n",
    "        print(f\"Deleting existing data for: {load_date}\")\n",
    "\n",
    "        delete_query = f\"\"\"\n",
    "            DELETE FROM {TABLE_NAME}\n",
    "            WHERE businessdate = %s;\n",
    "        \"\"\"\n",
    "\n",
    "        cursor.execute(delete_query, (load_date,))\n",
    "        print(f\"Deleted rows: {cursor.rowcount}\")\n",
    "\n",
    "        print(\"Starting COPY insert...\")\n",
    "\n",
    "        buffer = io.StringIO()\n",
    "        df.to_csv(\n",
    "            buffer,\n",
    "            index=False,\n",
    "            header=False,\n",
    "            sep=\",\",\n",
    "            quoting=1\n",
    "        )\n",
    "        buffer.seek(0)\n",
    "\n",
    "        copy_query = f\"\"\"\n",
    "            COPY {TABLE_NAME} (\n",
    "                branchName,\n",
    "                branchCode,\n",
    "                invoiceNumber,\n",
    "                invoiceDate,\n",
    "                invoiceType,\n",
    "                directChargeAmount,\n",
    "                chargeAmount,\n",
    "                grossAmount,\n",
    "                discountAmount,\n",
    "                taxAmount,\n",
    "                netAmount,\n",
    "                roundOffAmount,\n",
    "                totalAmount,\n",
    "                channel,\n",
    "                status,\n",
    "                sessionLabel,\n",
    "                customerId,\n",
    "                customerName,\n",
    "                Hour,\n",
    "                BusinessDate,\n",
    "                date,\n",
    "                BusinessBrand,\n",
    "                Source,\n",
    "                Channel_Category\n",
    "            )\n",
    "            FROM STDIN WITH (FORMAT CSV)\n",
    "        \"\"\"\n",
    "\n",
    "        cursor.copy_expert(copy_query, buffer)\n",
    "\n",
    "        print(\"Running store master update...\")\n",
    "\n",
    "        cursor.execute(\n",
    "            \"SELECT update_sales_from_master(%s);\",\n",
    "            (load_date,)\n",
    "        )\n",
    "\n",
    "        conn.commit()\n",
    "\n",
    "        print(f\"Inserted rows: {len(df)}\")\n",
    "        print(\"ETL completed successfully.\")\n",
    "\n",
    "    except Exception as e:\n",
    "        if conn:\n",
    "            conn.rollback()\n",
    "\n",
    "        print(f\"Load failed: {str(e)}\")\n",
    "        raise\n",
    "\n",
    "    finally:\n",
    "        if cursor:\n",
    "            cursor.close()\n",
    "\n",
    "        if conn:\n",
    "            conn.close()\n",
    "\n",
    "        print(\"Database connection closed.\")\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# MAIN\n",
    "# =====================================================\n",
    "\n",
    "def main():\n",
    "    print(\"====================================\")\n",
    "    print(\"STARTING DAILY SALES ETL\")\n",
    "    print(\"====================================\")\n",
    "\n",
    "    print(f\"Load Date: {LOAD_DATE}\")\n",
    "\n",
    "    df = get_all_sales(LOAD_DATE)\n",
    "\n",
    "    if df.empty:\n",
    "        raise Exception(\"No sales data received from API\")\n",
    "\n",
    "    df = process_data(df)\n",
    "\n",
    "    load_to_postgres(df)\n",
    "\n",
    "    print(\"====================================\")\n",
    "    print(\"ETL FINISHED SUCCESSFULLY\")\n",
    "    print(\"====================================\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
